// LOCALHOST
### Get all users
GET http://localhost:3000/users


### Get contact by ID
GET http://localhost:3000/users/686ff30f4b5239149b321ec8


### Create contact
POST http://localhost:3000/users HTTP/1.1
content-type: application/json

{
  "firstName": "Sylama",
  "lastName": "Mariesy",
  "email": "sylaaa@gmail.com",
  "favoriteColor": "blue",
  "birthday": "01/10/07"
}

### PUT contact
PUT http://localhost:3000/users/686ff82b4b5239149b321ecc HTTP/1.1
content-type: application/json

{
  "firstName": "Sylama",
    "lastName": "Mariesy",
    "email": "sylaaa@gmail.com",
    "favoriteColor": "yellow",
    "birthday": "01/10/07"
}

### Delete contact
DELETE http://localhost:3000/users/686ff82b4b5239149b321ecc HTTP/1.1